# app/Dockerfile

FROM python:3.9-slim

EXPOSE 8502

WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    software-properties-common \
    git \
    && rm -rf /var/lib/apt/lists/*

COPY ./requirements.manager_app.txt  /app/requirements.manager_app.txt
RUN pip3 install -r requirements.manager_app.txt

# RUN git clone https://github.com/streamlit/streamlit-example.git .

COPY . /app



COPY DataApp/config.ini /app/DataApp 

WORKDIR /app/DataApp
ENV PYTHONPATH=../
ENTRYPOINT ["streamlit", "run", "streamlit_manager_app.py", "--server.port=8502", "--server.address=0.0.0.0"]
